LangString addOrReinstall ${LANG_KOREAN} "구성 요소 추가 또는 다시 설치"
LangString alreadyInstalled ${LANG_KOREAN} "이미 설치됨"
LangString alreadyInstalledLong ${LANG_KOREAN} "${PRODUCTNAME} ${VERSION}이(가) 이미 설치되어 있습니다. 수행할 작업을 선택한 후 다음을 클릭하세요."
LangString appRunning ${LANG_KOREAN} "{{product_name}}이(가) 실행 중입니다. 먼저 종료한 후 다시 시도하세요."
LangString appRunningOkKill ${LANG_KOREAN} "{{product_name}}이(가) 실행 중입니다.$\n확인을 클릭하면 종료합니다."
LangString chooseMaintenanceOption ${LANG_KOREAN} "수행할 유지 관리 작업을 선택하세요."
LangString choowHowToInstall ${LANG_KOREAN} "${PRODUCTNAME} 설치 방법을 선택하세요."
LangString createDesktop ${LANG_KOREAN} "바탕 화면 바로 가기 만들기"
LangString dontUninstall ${LANG_KOREAN} "제거하지 않음"
LangString dontUninstallDowngrade ${LANG_KOREAN} "제거하지 않음(이 설치 프로그램에서는 제거하지 않은 다운그레이드를 지원하지 않습니다)"
LangString failedToKillApp ${LANG_KOREAN} "{{product_name}}을(를) 종료하지 못했습니다. 먼저 종료한 후 다시 시도하세요."
LangString installingWebview2 ${LANG_KOREAN} "WebView2를 설치하는 중..."
LangString newerVersionInstalled ${LANG_KOREAN} "더 새로운 버전의 ${PRODUCTNAME}이(가) 이미 설치되어 있습니다. 이전 버전을 설치하려면 먼저 현재 버전을 제거하는 것이 좋습니다. 수행할 작업을 선택한 후 다음을 클릭하세요."
LangString older ${LANG_KOREAN} "이전"
LangString olderOrUnknownVersionInstalled ${LANG_KOREAN} "시스템에 $R4 버전의 ${PRODUCTNAME}이(가) 설치되어 있습니다. 설치 전에 현재 버전을 제거하는 것이 좋습니다. 수행할 작업을 선택한 후 다음을 클릭하세요."
LangString silentDowngrades ${LANG_KOREAN} "이 설치 프로그램에서는 다운그레이드를 지원하지 않습니다. 그래픽 설치 프로그램을 사용하세요.$\n"
LangString unableToUninstall ${LANG_KOREAN} "제거할 수 없습니다!"
LangString uninstallApp ${LANG_KOREAN} "${PRODUCTNAME} 제거"
LangString uninstallBeforeInstalling ${LANG_KOREAN} "설치하기 전에 제거"
LangString unknown ${LANG_KOREAN} "알 수 없음"
LangString webview2AbortError ${LANG_KOREAN} "WebView2 설치에 실패했습니다. 앱을 실행하려면 WebView2가 필요합니다. 설치 프로그램을 다시 실행하세요."
LangString webview2DownloadError ${LANG_KOREAN} "오류: WebView2 다운로드 실패 - $0"
LangString webview2DownloadSuccess ${LANG_KOREAN} "WebView2 부트스트래퍼를 성공적으로 다운로드했습니다."
LangString webview2Downloading ${LANG_KOREAN} "WebView2 부트스트래퍼를 다운로드하는 중..."
LangString webview2InstallError ${LANG_KOREAN} "오류: WebView2 설치 실패(종료 코드: $1)"
LangString webview2InstallSuccess ${LANG_KOREAN} "WebView2를 설치했습니다."
LangString deleteAppData ${LANG_KOREAN} "앱 데이터 삭제"
